package org.example.ridinginfomation.Garmin.VO;

import lombok.Data;
import lombok.Getter;
import lombok.Setter;

@Data
@Setter
@Getter
public class ActivityVO {
    private long activityId;
    private String activityDate;
    private String activityName;
    private String activityType;
    private String activityDescription;
    private Double elapsedTime;
    private Double distance;
    private Double maxHeartRate;
    private Double relativeEffort;
    private Boolean commute;
    private String activityPrivateNote;
    private String activityGear;
    private String filename;
    private Double athleteWeight;
    private Double bikeWeight;
    private Double elapsedTime2;
    private Double movingTime;
    private Double distance2;
    private Double maxSpeed;
    private Double averageSpeed;
    private Double elevationGain;
    private Double elevationLoss;
    private Double elevationLow;
    private Double elevationHigh;
    private Double maxGrade;
    private Double averageGrade;
    private Double averagePositiveGrade;
    private Double averageNegativeGrade;
    private Double maxCadence;
    private Double averageCadence;
    private Double maxHeartRate2;
    private Double averageHeartRate;
    private Double maxWatts;
    private Double averageWatts;
    private Double calories;
    private Double maxTemperature;
    private Double averageTemperature;
    private Double relativeEffort2;
    private Double totalWork;
    private Integer numberOfRuns;
    private Double uphillTime;
    private Double downhillTime;
    private Double otherTime;
    private Integer perceivedExertion;
    private String type;
    private String startTime;
    private Double weightedAveragePower;
    private Integer powerCount;
    private Boolean preferPerceivedExertion;
    private Double perceivedRelativeEffort;
    private Boolean commute2;
    private Double totalWeightLifted;
    private Boolean fromUpload;
    private Double gradeAdjustedDistance;
    private String weatherObservationTime;
    private String weatherCondition;
    private Double weatherTemperature;
    private Double apparentTemperature;
    private Double dewpoint;
    private Double humidity;
    private Double weatherPressure;
    private Double windSpeed;
    private Double windGust;
    private Double windBearing;
    private Double precipitationIntensity;
    private String sunriseTime;
    private String sunsetTime;
    private Double moonPhase;
    private String bike;
    private String gear;
    private Double precipitationProbability;
    private String precipitationType;
    private Double cloudCover;
    private Double weatherVisibility;
    private Integer uvIndex;
    private Double weatherOzone;
    private Integer jumpCount;
    private Double totalGrit;
    private Double averageFlow;
    private Boolean flagged;
    private Double averageElapsedSpeed;
    private Double dirtDistance;
    private Double newlyExploredDistance;
    private Double newlyExploredDirtDistance;
    private Integer activityCount;
    private Integer totalSteps;
    private Double carbonSaved;
    private Double poolLength;
    private Double trainingLoad;
    private Double intensity;
    private String averageGradeAdjustedPace;
    private Double timerTime;
    private Integer totalCycles;
    private String media;
}
